### PR TITLE
check root on Linux and restart script as root

### PR DESCRIPTION
**Pull request by sasa8810**

### CODE REVIEW

**Review by BananaOnGitHub — APPROVED** [review]
finally

**Comment by alex-free** [comment]
Wouldn't it just be better if you prevented execution unless $EUID = 0 and uname returns Linux? Just dump a message "palera1n requires root privileges on Linux to access your device".

**Comment by BananaOnGitHub** [comment]
> Wouldn't it be better if you prevented execution if $EUID != 0 and uname returns Linux? Just dump a message "palera1n requires root privileges on Linux to access your device".

it would be more efficient this way

**Comment by alex-free** [comment]
> > Wouldn't it be better if you prevented execution if $EUID != 0 and uname returns Linux? Just dump a message "palera1n requires root privileges on Linux to access your device".
> 
> it would be more efficient this way

In my opinion, informing the user of the proper usage is more proper. Another gripe with this is that it requires yet another dependency, 'caffeinate'. I do see why it has been added, but it just all seems really complicated and it adds yet another external dependency. 

Is it really that bad for the UX to be like this:

1) User doesn't read docs, executes palera1n without root privileges on Linux.
2) Palera1n informs the user that it needs root privileges on Linux.
3) User does sudo !!
4) User in the future now knows to execute palera1n with root privileges on Linux.

**Pull request closed without merging**
