### PR TITLE
fix dyld: cannot load 'Kernel64Patcher' (load command 0x80000034 is u…

### PR DESCRIPTION
**Pull request by ghost**
…nknown)

fix dyld: cannot load 'iBootpatch2' (load command 0x80000034 is unknown)

[guacaplushy](https://github.com/guacaplushy) should be credited for helping me recompile these binaries

### CODE REVIEW

**Comment by guacaplushy** [comment]
tested on high sierra im guessing?

**Comment by itsnebulalol** [comment]
Both work on my mac, but can you chmod the binaries?

**Comment by netsirkl64** [comment]
image

**Comment by guacaplushy** [comment]
git update-index --chmod=+x <file>

**Pull request closed without merging**
