### PR TITLE
fix stderr not going to log file

### PR DESCRIPTION
**Pull request by nyuszika7h**

### CODE REVIEW

**Review by AlexSpaces — COMMENTED** [review]
Did you change it?

**Comment by X7HYPER** [comment]
I'll log file and process also validly sign it too

**Comment by X7HYPER** [comment]
(gr8-(J͜͡O͜͡B͜͡)

**Comment by X7HYPER** [comment]
> Did you change it?

Yᖇᔕ ᔕᕼOᑌᒪᗪ ᗷE OK ᑎOᗯ

**Pull request merged**
