### PR TITLE
Create cmake-single-platform.yml

### PR DESCRIPTION
**Pull request by TETRIS45666**

### CODE REVIEW

**Comment by TETRIS45666** [comment]
Commit.md

**Comment by TETRIS45666** [comment]
Commit.md

**Review by TETRIS45666 — COMMENTED** [review]
Commit.md

**Review by TETRIS45666 — COMMENTED** [review]
Merge.md

**Comment by ssalggnikool** [comment]
Do not make useless pull requests, thanks

**Review by TETRIS45666 — COMMENTED** [review]
Push.md

**Review by TETRIS45666 — COMMENTED** [review]
Push.md

**Pull request closed without merging**
