### PR TITLE
Use inetcat instead of iproxy

### PR DESCRIPTION
**Pull request by MrMan314**
Picks a random port number between 1024-65535 (if my logic is correct)

### CODE REVIEW

**Comment by asdfugil** [comment]
just use inetcat

**Comment by MrMan314** [comment]
Ok, I will look into it

**Comment by MrMan314** [comment]
Semi-done (just need to add the binaries, i think)

**Comment by MrMan314** [comment]
Does anyone have the macOS binary for `inetcat`?

**Comment by MrMan314** [comment]
whoops

**Comment by talkra3** [comment]
> Picks a random port number between 1024-65535 (if my logic is correct)

**Comment by 0xallie** [comment]
duplicate of #297 fr

**Comment by MrMan314** [comment]
LMAO WHOOPS

**Pull request closed without merging**
