### PR TITLE
actually get the correct build number

### PR DESCRIPTION
**Pull request by guacaplushy**
sometimes, on specific versions getting the build id for the first device doesn't work. this will fix that by fetching the build id for the device

### CODE REVIEW

**Comment by guacaplushy** [comment]
@itsnebulalol please view yes thank

**Comment by itsnebulalol** [comment]
I have a better way of doing this without the 15.7* check

**Comment by guacaplushy** [comment]
> I have a better way of doing this without the 15.7* check

yes, but like what if you actually need one of the weird build ids

**Comment by guacaplushy** [comment]
how would that work @itsnebulalol

**Pull request closed without merging**
