### PR TITLE
Fix A8X 

### PR DESCRIPTION
**Pull request by samh06**
made a new pull request with my changes because it appears that now sasa's branch has merge conflicts from being left so long so I remade the PR with my changes instead

### CODE REVIEW

**Comment by sasa8810** [comment]
I was sleeping

> made a new pull request with my changes because it appears that now sasa's branch has merge conflicts from being left so long so I remade the PR with my changes instead 
i was sleeping fr

**Comment by samh06** [comment]
if you fix the merge conflicts ill close this

**Comment by samh06** [comment]
guessing no merge for this

ill just close

**Comment by itsnebulalol** [comment]
didn’t see this, will merge

**Pull request merged**
