### PR TITLE
fix get_sigcheck_patch A9(X) bug on 16.x

### PR DESCRIPTION
**Pull request by ghost**
all credit goes to plooshi for the bug fix
all credit goes to woofy for making a working darwin bin :3

### CODE REVIEW

**Comment by danio0701** [comment]
Hi, I get same error:

[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
main: Starting...
iOS 16 iBoot detected!
getting get_sigcheck_patch() patch
main: Error doing patch_rsa_check()!
[-] An error occurred
[-] An error occurred
[*] A failure log has been made. If you're going ask for help, please attach the latest log.

Same issue for all iOS 16 iPads. Any solution?

**Comment by guacaplushy** [comment]
this is only specific to A9(X) ipads from my testing

**Comment by danio0701** [comment]
I get this error for every iPad cpu A9-A10X with iOS 16.0b6

**Comment by danio0701** [comment]
My mistake, I had outdated script. Only A9X not work

**Comment by Shaneee** [comment]
Confirmed to work on iPad6,3 on 16.2.

**Comment by fxlupo** [comment]
Because of the prevous post from Shaneee, I upgraded from 16.1 to 16.2
But no change. Same Error. iPad6,3 on 16.2

[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
main: Starting...
iOS 16 iBoot detected!
getting get_sigcheck_patch() patch
main: Error doing patch_rsa_check()!
[-] An error occurred
[-] An error occurred

**Comment by Shaneee** [comment]
> Because of the prevous post from Shaneee, I updated from 16.1 to 16.2 But no change. Same Error. iPad6,3 on 16.2
> 
> btw. I'm on a MAC
> 
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 Found the USB handle. main: Starting... iOS 16 iBoot detected! getting get_sigcheck_patch() patch main: Error doing patch_rsa_check()! [-] An error occurred [-] An error occurred

I'm also using macOS. Specifically 13.2 (a) Beta (22D7750270d). Apart from replacing the binary from netsirkl64's branch no other changes were made.

**Comment by Admin-233** [comment]
Same error on iPad6,11 on 16.2
script run on 5.18.0-kali5-amd64

**Comment by BigBoiMan123** [comment]
Kali has other issues

**Comment by thjvjnam** [comment]
Mine is this errors either : 

Now you can boot untrusted images.
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
main: Starting...
iOS 16 iBoot detected!
getting get_sigcheck_patch() patch
main: Error doing patch_rsa_check()!
[-] An error occurred
[-] An error occurred
[*] A failure log has been made. If you're going ask for help, please attach the latest log.

**Pull request closed without merging**
