### PR TITLE
add stuck at creating ramdisk error solution for amd x86_64 to COMMONISSUES.md

### PR DESCRIPTION
**Pull request by alex-free**
Worked for me for AMD Ryzen 5 5600H/Fedora Linux x86_64/iPhone 6S Plus/iOS 15.7.3. All of the info online saying you can't use AMD is wrong!

### CODE REVIEW

**Comment by flowerible** [comment]
Mobile processors are known to work better than the desktop variants

**Comment by flowerible** [comment]
Which is why stated in the readme it's `AMD CPUs have an issue [with (likely) their USB controllers] that causes them to have a very low success rate with checkm8. It is not recommended that you use them with palera1n.`

**Comment by alex-free** [comment]
> Which is why stated in the readme it's `AMD CPUs have an issue [with (likely) their USB controllers] that causes them to have a very low success rate with checkm8. It is not recommended that you use them with palera1n.`

Even if so, this is still a valid workaround that isn't documented anywhere else. Look at all of these Reddit threads, I think this is useful. None of these threads have a solution and I'm sure this could help other users.

https://www.reddit.com/r/jailbreak/comments/zcezy8/discussion_palar1n_stuck_at_creating_ramdisk_for/

https://www.reddit.com/r/jailbreak/comments/xzlrjx/question_stuck_on_creating_ramdisk/

https://www.reddit.com/r/jailbreak/comments/zbw05j/help_palera1n_after_creating_ramdisk_i_get_stuck/

https://www.reddit.com/r/jailbreak/comments/ywcwoq/help_trying_to_jailbreak_with_palera1n_i_get_to/

**Comment by flowerible** [comment]
Never said this was invalid, was just informing you that mobile processors have a better success rate, unfortunate that not many know of that.

Still a welcome changed for commonissues for those with AMD processors with issues.

Also, would recommend saying that if this doesn't work then try and plug a USB-A cable directly on the motherboard (mostly for desktop computers), if issue still persists unfortunately you may need to get an intel machine.

**Comment by alex-free** [comment]
> Never said this was invalid, was just informing you that mobile processors have a better success rate, unfortunate that not many know of that.
> 
> Still a welcome changed for commonissues for those with AMD processors with issues.
> 
> Also, would recommend saying that if this doesn't work then try and plug a USB-A cable directly on the motherboard (mostly for desktop computers), if issue still persists unfortunately you may need to get an intel machine.

Interesting, that is actually what I had to do with my laptop. Disconnect and then reconnect the lighting cable directly from the computer itself, just doing that on the iPhone side did nothing.

I reworded it a bit, let me know if you have any other improvements that I should add to the document.

I will say though, this is 100% for me so far at least on my laptop to get palera1n working.  I did add all info however that you informed me of.

**Review by BananaOnGitHub — CHANGES_REQUESTED** [review]
saying `palera1n.sh` is awkward, i would just say palera1n

**Comment by alex-free** [comment]
> saying `palera1n.sh` is awkward, i would just say palera1n

Agreed, reworded this again.

**Comment by junepark678** [comment]
Maybe for technical people add an explanation that gaster can't be used on amd?

**Comment by alex-free** [comment]
> Maybe for technical people add an explanation that gaster can't be used on amd?

The whole point of the workaround is that you can use it on amd though, I think this covers everything.

**Pull request closed without merging**
