### PR TITLE
added gum to make it alive

### PR DESCRIPTION
**Pull request by olivertzeng**
[gum](https://github.com/charmbracelet/gum)

### CODE REVIEW

**Comment by olivertzeng** [comment]
gum is a tool to make shellscripts glamourous thanks to https://github.com/charmbracelet/gum

things added

- `gum style`
- `gum format`
- `gum input`
- `gum table`
- `gum choose`
- `gum spin`
- `gum join`

**Comment by Beast9265** [comment]
cum

**Comment by olivertzeng** [comment]
> cum

oh mr beast

**Comment by Beast9265** [comment]
i am not mr beast what are you saying

**Comment by olivertzeng** [comment]
> i am not mr beast what are you saying

i mean you are mister beast right? Your name is Beast so i called you Mr.Beast am i right?
@Beast9265

**Comment by typicalcooper** [comment]
wtf is happening

**Comment by olivertzeng** [comment]
> wtf is happening

you look like zuckerberg

**Pull request closed without merging**
