### PR TITLE
grammer

### PR DESCRIPTION
**Pull request by m00nl1ghts**

### CODE REVIEW

**Review by SleepLessGunner666 — COMMENTED** [review]
Gg

**Comment by kbtbc** [comment]
ironically, it's spelled 'grammar'

**Comment by m00nl1ghts** [comment]
ironically, no one asked

**Comment by plooshi** [comment]
ironically, i am here to say that this makes the grammar worse

**Review by squirtla — APPROVED** [review]

**Comment by ebrahimalablly** [comment]
في جمعة، ٣١ مارس، ٢٠٢٣ في ١:٠٦ ص، كتب squirtla ***@***.***>:

**Pull request merged**
