### PR TITLE
Increasing stability

### PR DESCRIPTION
**Pull request by vadim-a-yegorov**

### CODE REVIEW

**Comment by vadim-a-yegorov** [comment]
* Check network connection and wait for network
* Rerun entering DFU stage after fail
* Misc

**Comment by itsnebulalol** [comment]
Looks fine aside from it pinging 1.1.1.1 every time its going to download something. Maybe limit the checks a bit

**Comment by asdfugil** [comment]
it also doesn’t check dns resolution, ping something like connectivity-check.ubuntu.com instead

**Comment by itsnebulalol** [comment]
Just have it ping static.palera.in honestly, if it's down the script wouldn't work without it anyway. it's barely down though too

**Comment by vadim-a-yegorov** [comment]
> Just have it ping static.palera.in honestly, if it's down the script wouldn't work without it anyway. it's barely down though too

Fixed

**Comment by vadim-a-yegorov** [comment]
Also I'm working on offline mode and auto-DFU feature and fixing not working fouldecrypt kerninfra, it requires tfp0

**Review by gipnomag — APPROVED** [review]

**Comment by itsnebulalol** [comment]
> auto-DFU feature by sending corrupted payload to recovery
Can you explain how this works?

Is this ok to merge now?

**Comment by vadim-a-yegorov** [comment]
I approve merge for now.

Also check this:
https://blog.elcomsoft.com/2021/09/how-to-put-an-ios-device-with-broken-buttons-in-dfu-mode/
https://www.theiphonewiki.com/wiki/DFU_Mode#Enter_True_Hardware_DFU_Mode_Automatically

**Comment by itsnebulalol** [comment]
Your auto-DFU implementation works without restoring?

**Comment by vadim-a-yegorov** [comment]
> Your auto-DFU implementation works without restoring?

To get into DFU you should send corrupted LLB into recovery, then send normal LLB. I’ll add --auto-dfu flag

**Comment by rhino795527** [comment]
Palera1n.zip isn't installing after iCloud bypass with goldra1n

**Comment by guacaplushy** [comment]
> Palera1n.zip isn't installing after iCloud bypass with goldra1n

getting nebual to ban you from the org right now

**Comment by itsnebulalol** [comment]
already done

**Comment by junepark678** [comment]
good one ploosh

**Comment by itsnebulalol** [comment]
> To get into DFU you should send corrupted LLB into recovery, then send normal LLB. I’ll add --auto-dfu flag

Interesting, does this work all devices?

**Pull request merged**
