### PR TITLE
add Apple TV HD dfu instructions

### PR DESCRIPTION
**Pull request by tmm1**
on my device i can get past checkm8 and to kernel boot, but then it panics. waiting for serial cable to check logs

### CODE REVIEW

**Comment by 0xallie** [comment]
Hmm, not sure if there's much point in adding this right now considering palera1n doesn't currently work on tvOS. It's planned, but we hit an issue with frameworks not loading properly (the error refers to APFS.framework, but it probably just happens to be the first one in the list).

Also, you forgot Apple TV 4K 1st gen (CPID: 0x8011, BDID: 0x2).

**Review by 69camau — APPROVED** [review]

**Comment by 0xallie** [comment]
@i1p bro stop

**Comment by Spyninjaleader** [comment]
it does not let me use palera1n on my Mac

**Comment by 0x6ff** [comment]
can you just join the discord server (https://dsc.gg/palera1n) instead of commenting on random prs please

**Comment by Mohhdee** [comment]
How can I jailbreak my iPhone XS Max iOS 16.4.1a

**Comment by 0xallie** [comment]
You can't, also you're asking in the wrong place.

**Comment by RothSad110** [comment]
> on my device i can get past checkm8 and to kernel boot, but then it panics. waiting for serial cable to check logs

**Comment by ssalggnikool** [comment]
Hey! It's been a long time now, but palera1n now has Apple TV DFU instructions starting from: https://github.com/palera1n/palera1n/commit/05e1872ccbcf35ea7ded02edf29da3c0125f4529.
More proper DFU instructions for the ATV were done in a later commit being:  https://github.com/palera1n/palera1n/commit/053a495755008969bb63e409cfe973d32c867af6

Thank you for your initial PR, though we're now gonna close it due to not needing it anymore.

**Pull request closed without merging**
