### PR TITLE
fix COMMONISSUES.md stuff

### PR DESCRIPTION
**Pull request by BananaOnGitHub**

### CODE REVIEW

**Review by junepark678 — APPROVED** [review]
i would love this to happen lol

**Review by junepark678 — CHANGES_REQUESTED** [review]
have them rebase instead of reclone

**Review by junepark678 — APPROVED** [review]
MERGE THIS PLSPLS

**Comment by m00nl1ghts** [comment]
i sex for merge

**Comment by Beast9265** [comment]
> i sex for merge

don't sex for merge

**Comment by m00nl1ghts** [comment]
> > i sex for merge
> 
> don't sex for merge

yes i sex for merge

**Comment by junepark678** [comment]
don't post nsfw content

**Comment by junepark678** [comment]
Beast, get a contributor tag.

**Comment by Beast9265** [comment]
> Beast, get a contributor tag. it's for your own sake

no

**Comment by BananaOnGitHub** [comment]
what happened to this discussion section :fr:

**Comment by junepark678** [comment]
ikr banana

**Pull request merged**
