### PR TITLE
image of a chicken

### PR DESCRIPTION
**Pull request by 0xilis**
clearly the most important PR, i don't even know why palera1n.sh was released without this

### CODE REVIEW

**Comment by 0xilis** [comment]
this is too epic im closing

**Comment by ariezzalt** [comment]
i hate niggers

**Comment by ariezzalt** [comment]
NIGGERS

**Comment by ariezzalt** [comment]
NIGGERS

**Comment by ariezzalt** [comment]
NIGGERS

**Comment by ariezzalt** [comment]
NIGGERS

**Comment by ariezzalt** [comment]
NIGGERS

**Comment by ariezzalt** [comment]
NIGGERS

**Comment by ariezzalt** [comment]
NIGGERS

**Comment by ariezzalt** [comment]
NIGGERS

**Comment by ariezzalt** [comment]
NIGGERS

**Review by junepark678 — COMMENTED** [review]
# This is stupid, this commit needs to go
## this commit is breaking palera1n's IP

**Comment by ariezzalt** [comment]
NIGGERS

**Comment by ariezzalt** [comment]
NIGGERS

**Comment by ariezzalt** [comment]
NIGGERS

**Comment by ariezzalt** [comment]
U DELETING EM ARE U SERIOUS RIGHT NOW BRO

**Comment by ariezzalt** [comment]
GAY NIGGERS

**Comment by ariezzalt** [comment]
Who is this nerd? Alexia #nerd 
image
:nerd:

**Pull request closed without merging**
