### PR TITLE
Added new support link

### PR DESCRIPTION
**Pull request by vadim-a-yegorov**

### CODE REVIEW

**Review by squirtla — APPROVED** [review]

**Comment by ariezFR** [comment]
real report me alexia :pleading:

**Comment by ariezFR** [comment]
🥺

**Comment by ariezFR** [comment]
@everyone is pretty cool

**Comment by ariezFR** [comment]
> @everyone is cool

**Comment by ariezFR** [comment]
indeed did problem?

**Comment by ariezFR** [comment]
fuckin skid

**Comment by Arna13** [comment]
hi ariez :3

**Pull request closed without merging**
