### PR TITLE
fix not being able to get iPSW url

### PR DESCRIPTION
**Pull request by plooshi**
please test this, my bash can get the actual URL but i cannot test it on an actual device as i am not home and my devices don't have this issue.

### CODE REVIEW

**Comment by plooshi** [comment]
please update the ramdisk submodule too

**Comment by itsnebulalol** [comment]
This wouldn't work because the issue is that IPSW.me doesn't have the versions.

**Comment by plooshi** [comment]
@itsnebulalol it fetches the ipsw links from appledb, getting the build id from ipsw.me

**Comment by plooshi** [comment]
actually look at the commit

it fetches the actual list of devices for the version from ipsw.me, so it can get the build id

**Comment by itsnebulalol** [comment]
yeah i didn’t see that at first, sorry

**Comment by nyuszika7h** [comment]
why hardcode 15.7.1

**Comment by plooshi** [comment]
@itsnebulalol can you fix it to not hardcode 15.7.1
i made a mistake

**Pull request merged**
